### PR TITLE
Add normalize command

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
Reads a triangle and writes it back after dividing each distance by the max length of the two sequences.

### CODE REVIEW

**Comment by danieldanciu** [comment]
Shouldn't we just write the triangle directly normalized? :) I mean, other than a one-off, is this going to be needed in the future?

**Comment by RagnarGrootKoerkamp** [comment]
Yes, but the edit distances created by your code over the weekend weren't normalized, so I needed this. But I agree this doesn't necessarily need to be in master.

**Comment by danieldanciu** [comment]
Yes, yes, I agree the code was necessary, I am just not sure we need to
keep it in master.

**Comment by RagnarGrootKoerkamp** [comment]
let's not merge for now but keep the branch alive. If we need it again, we could also make a new `bin/` directory with some smaller binaries/'scripts' that handle these infrequent usages

**Pull request closed without merging**
